### ISSUE TITLE
What is the difference between ip_rot_equid_cylind_egrid and ip_rot_equid_cylind_grid?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#114]
What is the difference between ip_rot_equid_cylind_egrid and ip_rot_equid_cylind_grid?

They seem very similar. Documenation is wrong for ip_rot_equid_cylind_grid_mod (probably my mistake) but for ip_rot_equid_cylind_grid_mod it says:

```
!> @file
!! @brief Rotated equidistant cylindrical GRIB decoder and grid
!! coordinate transformations.
!! @author Mark Iredell, George Gayno, Kyle Gerheiser
!! @date July 2021

```

I need to know to fix documentation.

@GeorgeGayno-NOAA do you know? Thanks!

Part of #97.

**Comment by GeorgeGayno-NOAA** [comment]
`ip_rot_equid_cylind_egrid` is for Arakawa "E" staggering. `ip_rot_equid_cylind_grid` is for grids "A" thru "D".

The "E" stagger is a bit odd because the 'wind' points shift by half a grid box in each row. That makes the logic tricky. So the routine does its computations by rotating the grid by 45 degrees.

https://en.wikipedia.org/wiki/Arakawa_grids

**Comment by edwardhartnett** [comment]
OK, I have added this info to the docs. It's will be in the next doxygen PR.
