### ISSUE TITLE
Cleanup IPLIB

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [NOAA-EMC/NCEPLIBS-ip#12]
Version of the ``develop`` branch (3.0.0) should be >= version of ``release/public-v1`` branch (3.1.0).

**Comment by GeorgeGayno-NOAA** [comment]
1. And the release notes are named with the wrong version (and contain outdated information).
2. The unit tests no longer build because the configuration files they need were removed.  
3. The old build system was never removed.
4. Most of the 'readme' files are out-of-date.

Maybe this issue should be rename to "Cleanup IPLIB".

**Comment by kgerheiser** [comment]
Let me know if I can do anything. I know some of this is my doing.

**Comment by GeorgeGayno-NOAA** [comment]
@kgerheiser  I don't think the 'build_ip.sh" script and any of the files in ./Conf are used since CMake was added.  About a month ago, I tried to build the library using that script thinking it was a wrapper around the CMake build.  Maybe @Hang-Lei-NOAA still needs it?  Anyway, this is confusing for users.

**Comment by kgerheiser** [comment]
Oh, that's not what I thought it was. Admittedly I didn't look too closely. I thought those were the old build scripts.

**Comment by GeorgeGayno-NOAA** [comment]
> Let me know if I can do anything. I know some of this is my doing.

No problem.  This is not unexpected given the rush to get the public release done.

**Comment by GeorgeGayno-NOAA** [comment]
There is also a Makefile in ./src.  That has been superseded by CMake, correct?

**Comment by kgerheiser** [comment]
I deliberately kept the old build files around. I thought someone might want them while the CMake build is still being refined and we completely make the switch.

**Comment by DusanJovic-NOAA** [comment]
I think everything related to the old build shroud be just removed. If we do not remove it now who is going to maintain and test old Makefiles and those scripts in Conf?

**Comment by GeorgeGayno-NOAA** [comment]
I made some updates to the release notes for the V3.0.2 tag.  They should be moved to 'develop'.

**Comment by kgerheiser** [comment]
So, is the consensus to remove the old build system? @aerorahul @DusanJovic-NOAA @GeorgeGayno-NOAA  

I can go through the other libs too and leave only CMake.

**Comment by aerorahul** [comment]
I would create a tag at this point, with the old build system intact, and then purge the old build system

**Comment by GeorgeGayno-NOAA** [comment]
> So, is the consensus to remove the old build system? @aerorahul @DusanJovic-NOAA @GeorgeGayno-NOAA
> I can go through the other libs too and leave only CMake.

Yes, I would get rid of the old build system.  That is what I did when CMake was added to UFS_UTILS.

**Comment by edwardhartnett** [comment]
Has this been accomplished yet?

Is the develop branch still behind where it should be?
