### ISSUE TITLE
calls to Numerical Recipes need to be removed?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#220]
From @webisu 

SP: calls to Numerical Recipes need to be removed.
Code from an unknown origin need to be removed.

- [ ] src/lapack_gen.F - according to documentation, both subroutines are from NR.

**Comment by edwardhartnett** [comment]
@webisu how do we identify this code?

**Comment by AlexanderRichert-NOAA** [comment]
I found a couple subroutines from NR based on the comments (and verified that they are indeed based on the Numerical Recipes for Fortran routines, including the subroutine names). I added a checklist to the issue description to keep track. Right now I'm making a list of NR subroutines in the hopes that in other instances they will also have the same names. My guess is that any kind of linear algebra or Fourier-related routine should be checked.

**Comment by webisu** [comment]
NR codes will follow the NR naming convention.

As far as I am know, all source code files should
have some documentation of copyright status.  Any
source code file with no documentation is potentially
copyrighted code.  So manual inspection is required.

https://copyrightalliance.org/education/copyright-law-explained/copyright-basics/what-is-copyright-notice/#:~:text=Prior%20to%201989%20including%20a,a%20defense%20of%20innocent%20infringement
.

**Comment by edwardhartnett** [comment]
What changes to ip2/sp code are needed for wgrib2 to work with NCEPLIBS-ip?

Also wgrib2 code will need to change, as it must "use ip" now.

**Comment by webisu** [comment]
Right now wgrib2 can be compiled with
   1) without ip2lib and without splib
   2) with ip2lib and without splib
   3) with ip2lib and with splib
   4) with old iplib and without splib

Why so many options?
   1) old iplib is needed to handle rotated lat-lon using the NCEP local
grid template
            as used by NAM and RRFS
   2) new ip2lib is needed for better precision and is needed for rotated
lat-lon using
         the WMO grid template (regional FV3, Canadian and European
regional models)
   3) Until recently the splib was not included with wgrib2 sources because
of
            copyright issues.
   4) Without ip/sp, can compile wgrib2 without a fortran compiler.
   5) The wgrib2 library can be used by C, Fortran and python code.  This
code
           can call the ip or sp library independently of wgrib2.  There
will be name
           confusion with single and double precision versions of the
library and
          the old ip and new ip2 libraries.  This has been encountered by
other
          people and I have a simple code that read grib U/V and uses the
splib
          to get the stream function and velocity potential.

You could get rid of reason1 if the new ip2 could handle the NCEP rotated
lat-lon
grid template.    Probably ok if you simplify the options to
    1') without iplib, ip2lib and splib
    2') with ip2lib and splib
Then you can get rid of the "#ifdef USE_SPECTRAL" in my copy of the ip2
libraries.
