### ISSUE TITLE
Need ISO C wrappers for ipolatesv()

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip#235]
@webisu needs C wrappers for some more of the fortran subroutines, including ipolatesv() (@webisu what others?)

This is needed for wgrib2 to use NCEPLIBS-ip instead of an internal copy of the ip code.

@webisu has suggested that he will submit a PR. He was concerned with the level of unit testing required; only the correct calling needs to be tested in such a PR, not the entire functionality of the ipolatesv() function. I told @webisu that he could assume the Fortran code was already tested, and just writes a test to ensure the C code is correctly calling the Fortran code, and getting correct results.

**Comment by webisu** [comment]
Hi,
   ipolates and ipolatev need a method for C to call the fortran routines.
Much like the gdswiz_c routine.
Wesley

**Comment by edwardhartnett** [comment]
@AlexanderRichert-NOAA we need to get some C wrappers into ip, then do a release, so that wgrib2 can use them and we can do a release of wgrib2.

@webisu do you have the wrappers written?

FYI @AlysonStahl-NOAA is working on wgrib2 as well now...

**Comment by webisu** [comment]
Hi,
   My mistake.  I was looking at the ip2 library.  Yesterday I was
examining the ip library
and they have different entry points but (ex ipolates_grib2_single_field)
but the new
entry points have bind(c) on them.   So wgrib2 can use
ipolates(s|v)_grib2_single_field
instead of current ipolate(s|v)_.
   Did one test with the new ip library.  I seemed to work but there is
something I don't
understand about the build.
    Wesley

**Comment by webisu** [comment]
issue is closed, see previous comment
